### ISSUE TITLE
Deprecate tslint package and instead extend eslint one to also support typescript

### ISSUE THREAD

**Issue by janb87** [Kunstmaan/frontend-linters#11]
https://medium.com/palantir/tslint-in-2019-1a144c2317a9

It is clear that linting is a core part of the TypeScript/JavaScript developer experience, and so Palantir’s TSLint team met with the TypeScript core team in Redmond to discuss what the TypeScript/JavaScript convergence should mean for linting. The TypeScript community intends to meet JavaScript developers where they are, and ESLint is the tool of choice for JavaScript linting. In order to avoid bifurcating the linting tool space for TypeScript, we therefore plan to deprecate TSLint and focus our efforts instead on improving ESLint’s TypeScript support. There are both strategic and pragmatic reasons why we believe this is the correct path forward:

**Comment by janb87** [comment]
Snipsonian already uses eslint instead of tslint (extending the eslint package).

See https://github.com/Kunstmaan/snipsonian/blob/master/.eslintrc.js

**Comment by janb87** [comment]
AirBnb version of eslint for typescript:
https://www.npmjs.com/package/eslint-config-airbnb-typescript

**Comment by diskwriter** [comment]
Fixed in #12
